ls:
  .js: lowercase
  .json: lowercase
  .css: lowercase
  .html: lowercase
  .ico: lowercase
  .jpg: lowercase
  .png: lowercase
  .svg: lowercase
  .tff: lowercase
  .woff: lowercase
  .woff2: lowercase

ignore: 
  - .git
  - public
  - node_modules
  - packages/plugin-babel/node_modules
  - packages/init/node_modules
  - packages/plugin-typescript/node_modules