import { createHash } from "node:crypto";

/**
 * Generates a hash of the input string.
 * @param {string} inputString - The string to hash.
 * @param {number} [bytes=6] - Number of bytes to be generated by the hash (default: 6).
 * Note: This specifies the number of bytes, not the length of the hash.
 * The hash length in characters depends on the bytes and is approximately `(bytes * 8 / 6)` when encoded in base64url.
 * @returns {string} A base64url-encoded hash of the input string.
 */
function hashString(inputString, bytes = 6) {
  return createHash("shake256", { outputLength: bytes }).update(inputString).digest("base64url");
}

export { hashString };
