name: 💡 Feature Request
description: Submit a new feature request for Greenwood.
title: "Support x in Greenwood"
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for submitting a feature request to Greenwood!
  - type: textarea
    id: summary
    attributes:
      label: Motivation
      description: Please provide a summary of the feature you are requesting and use case(s).
      placeholder: It would be great if Greenwood could do...
    validations:
      required: true
  - type: textarea
    id: Motivation
    attributes:
      label: Technical Design
      description: Detail usage within a Greenwood project and the API design you have in mind.
      placeholder: I want to use the feature like this...
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Please provide any additional details, links, or resources that may be helpful for consideration of this feature.
    validations:
      required: false
