name: Continous Integration - Bun
on:
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      # still using Yarn since we specifically rely on Yarn workspaces
      - name: Install Dependencies
        run:  yarn install --frozen-lockfile && yarn lerna bootstrap

      - name: Test
        run: bun run test

      - name: Build
        run: bun run build