name: Continuous Integration (Loaders - Deno)

on: [pull_request]

jobs:
  deno:
    runs-on: ubuntu-latest
    env:
      PUPPETEER_EXECUTABLE_PATH: /usr/bin/google-chrome-unstable
      PUPPETEER_SKIP_DOWNLOAD: "true"

    steps:
      - uses: actions/checkout@v6

      - name: Install Chromium Library Dependencies
        run: sh ./.github/workflows/chromium-lib-install.sh

      - name: Use Node.js 24
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: yarn

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
          cache-hash: ${{ hashFiles('yarn.lock') }}

      - uses: pnpm/action-setup@v6
        name: Install pnpm
        with:
          version: latest

      - name: Installing project dependencies
        run: yarn install --frozen-lockfile

      - name: Test
        run: deno task test:loaders:deno
