name: Continuous Integration (Loaders)

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [24, 26]

    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
      - uses: pnpm/action-setup@v6
        name: Install pnpm
        with:
          version: latest
      - name: Installing project dependencies
        run: |
          yarn install --frozen-lockfile
      - name: Install Chrome from Puppeteer
        run: |
          bash ./.github/workflows/chromium-lib-install.sh
      - name: Test
        run: |
          yarn test:loaders
          yarn test:loaders:options
