name: Continuous Integration Windows (Loaders)

on: [pull_request]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node: [22]

    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
      - uses: pnpm/action-setup@v6
        name: Install pnpm
        with:
          version: latest
      - name: Installing project dependencies
        run: |
          yarn install --frozen-lockfile --network-timeout 1000000
      - name: Install Puppeteer Browser
        # manually install chrome binary
        run: |
          npx puppeteer browsers install chrome
      - name: Test
        run: |
          yarn test:loaders:win
