name: Continuous Integration Windows (TypeScript)

on: [pull_request]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node: [22]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Installing project dependencies
        run: |
          yarn install --frozen-lockfile --network-timeout 1000000 && yarn lerna bootstrap
      - name: Test
        run: |
          yarn test:typescript:win
