name: Continuous Integration Windows (Loaders)

on: [pull_request]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node: [22]

    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"
      - name: Installing project dependencies
        run: |
          yarn install --frozen-lockfile --network-timeout 1000000
      - name: Test
        run: |
          yarn test:loaders:win
      - name: Test fixed
        if: ${{ always() }}
        run: |
          yarn test:loaders:win2
