name: Continuous Integration

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [24, 26]

    steps:
      - uses: actions/checkout@v6
      - name: Install Chromium Library Dependencies
        run: |
          sh ./.github/workflows/chromium-lib-install.sh
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
      - uses: pnpm/action-setup@v6
        name: Install pnpm
        with:
          version: latest
      - name: Installing project dependencies
        run: |
          pnpm i
        # use path installed by chromium-lib-install.sh
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
          PUPPETEER_EXECUTABLE_PATH: "/usr/bin/google-chrome-unstable"
      - name: Lint
        run: |
          pnpm run lint
      - name: Check Formatting
        run: |
          pnpm run format:check
      - name: Test
        run: |
          pnpm run test
      - name: Build
        run: |
          pnpm run clean && pnpm run build
      - name: Commitlint Check
        if: github.event_name == 'push'
        run: pnpm run commit:lint
